name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a single line
          - run: echo "Hi"
      - name: Run a multi line
          - run: |
              echo "Hi"
              echo "How are you"